#!/bin/sh

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Processing format code...."

# Run prettier and get the output and return code
prettier=$(npm run format:fix)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "\n${RED}Prettier failed:${NC}"
	echo "$prettier\n"
	pass=false
else
    printf "$prettier"
	printf "${GREEN}\nPrettier passed.${NC}\n"
fi

echo "\nRunning Linters....\n"

# Run tslint and get the output and return code
tslint=$(npm run lint)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "\n${RED}Lint failed:${NC}"
	echo "$tslint\n"
	pass=false
else
	printf "${GREEN}All lint passed.${NC}\n"
fi

# Run stylelint and get the output and return code
stylelint=$(npm run lint:styles --force)
ret_code=$?

if [ $ret_code != 0 ]; then
	printf "${RED}Stylelint failed:${NC}"
	echo "$stylelint\n"
	pass=false
else
	printf "${GREEN}All stylelint passed.${NC}\n"
fi

echo "\n"
# If there were no failures, it is good to commit
if $pass; then
	exit 0
fi

exit 1