export let toolbarOptions = {
    bold: 'bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'strikethrough',
    color: 'forecolor',
    background: 'backcolor',
    // math: 'eqneditor',
    ol: 'numlist',
    ul: 'bullist',
    table: 'table',
    alignleft: 'alignleft',
    aligncenter: 'aligncenter',
    alignright: 'alignright',
    alignjustify: 'alignjustify',
    outdent: 'outdent',
    indent: 'indent',
    formatselect: 'formatselect',
    fontselect: 'fontselect',
    fontsize: 'fontsizeselect'
};
